# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    ls -la
    git remote add azure-dev-ops git@ssh.dev.azure.com:v3/lanceolata-old/carbon-event-scout/carbon-event-scout
    git push azure-dev-ops --all
    git push azure-dev-ops --tags
  displayName: 'Push to Azure DevOps repo'
