# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true

pool:
  vmImage: 'ubuntu-latest'

steps:

# Install SSH key
# Install an SSH key prior to a build or deployment
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H'
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPGaDDsyzpknxPQuPIqfDiKqJVp2dK5LcjSKdHqHA3GXWw7nCmFhoJNt5i4sLWVtRxqDHGzOrglZkRyf+NZFw5bAC/OI1X4tppWlwy9kZvEwE+oNZqku9O7hgb9D7PMDBGN/pA8RNgLARgxecCIbgVoY3sHXOLg0xtY6wx9oSZZ+SybSxTy49RRSdLTml0xr1SHyu5M6sgAEvKioHTlTdvC68QVTU08EimRd+4HTWdlm7wYw57wjBtEarvK59PlRI7hB/FFJQIbCKBoulQXMvOfK+DCppyTYUjpZoftLLFMpC1YBhVHsj9xeQForZ2LYBIVrepzH8Z6ffsqdFml/7R owenholloway@Owens-HackPro.local'
    #sshPassphrase: # Optional
    sshKeySecureFile: 'id_rsa'

- script: |
    ls -la
    git remote add azure-dev-ops git@ssh.dev.azure.com:v3/lanceolata-old/carbon-event-scout/carbon-event-scout
    git push azure-dev-ops --all
    git push azure-dev-ops --tags
  displayName: 'Push to Azure DevOps repo'
